apiVersion: apps/v1
kind: Deployment
metadata:
  name: fridge2fork-admin-web
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: web
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"