apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

bases:
  - ../../base

commonLabels:
  environment: dev

images:
  - name: fridge2fork-admin-web
    newName: YOUR_DOCKERHUB_USERNAME/fridge2fork-admin-web-dev
    newTag: latest

patchesStrategicMerge:
  - deployment-patch.yaml
  - hpa-patch.yaml

configMapGenerator:
  - name: fridge2fork-config
    behavior: merge
    literals:
      - node_env=development