apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  project: fridge2fork
  component: admin-web

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml