# Generated by Django 5.2.7 on 2025-10-04 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='비회원인 경우 세션 키', max_length=255, null=True, verbose_name='세션 키')),
                ('feedback_type', models.CharField(choices=[('BUG', '버그 리포트'), ('FEATURE', '기능 제안'), ('IMPROVEMENT', '개선 제안'), ('OTHER', '기타')], db_index=True, default='OTHER', max_length=20, verbose_name='피드백 유형')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('contact_email', models.EmailField(blank=True, help_text='답변 받을 이메일 (선택)', max_length=255, null=True, verbose_name='연락처 이메일')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='생성일시')),
                ('user', models.ForeignKey(blank=True, help_text='회원인 경우 사용자 정보', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '피드백',
                'verbose_name_plural': '피드백',
                'db_table': 'system_feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
