# Generated by Django 5.2.7 on 2025-10-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='레코드가 생성된 시각', verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='레코드가 마지막으로 수정된 시각', verbose_name='수정일시')),
                ('ad_type', models.CharField(choices=[('BANNER_TOP', '배너 광고 (상단)'), ('BANNER_BOTTOM', '배너 광고 (하단)'), ('INTERSTITIAL_1', '전면 광고 1'), ('INTERSTITIAL_2', '전면 광고 2'), ('NATIVE_1', '네이티브 광고 1'), ('NATIVE_2', '네이티브 광고 2')], max_length=50, verbose_name='광고 타입')),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS')], db_index=True, max_length=20, verbose_name='플랫폼')),
                ('ad_unit_id', models.CharField(help_text='AdMob 광고 단위 ID (예: ca-app-pub-xxx/yyy)', max_length=255, verbose_name='광고 단위 ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='활성화 여부')),
            ],
            options={
                'verbose_name': '광고 설정',
                'verbose_name_plural': '광고 설정',
                'db_table': 'system_ad_config',
                'ordering': ['platform', 'ad_type'],
                'indexes': [models.Index(fields=['platform', 'is_active'], name='system_ad_c_platfor_dea89f_idx')],
                'unique_together': {('ad_type', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='레코드가 생성된 시각', verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='레코드가 마지막으로 수정된 시각', verbose_name='수정일시')),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS')], db_index=True, max_length=20, verbose_name='플랫폼')),
                ('version_name', models.CharField(help_text='예: 1.2.3', max_length=50, verbose_name='버전명')),
                ('version_code', models.IntegerField(help_text='비교용 정수 (예: 1.2.3 → 10203)', verbose_name='버전 코드')),
                ('min_supported_version_code', models.IntegerField(help_text='이 버전보다 낮으면 강제 업데이트', verbose_name='최소 지원 버전 코드')),
                ('force_update', models.BooleanField(default=False, verbose_name='강제 업데이트 여부')),
                ('update_message', models.TextField(help_text='사용자에게 표시할 업데이트 메시지', verbose_name='업데이트 안내 메시지')),
                ('download_url', models.URLField(help_text='앱 스토어 URL', max_length=500, verbose_name='다운로드 URL')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='최신 버전만 True로 설정', verbose_name='활성화 여부')),
                ('release_date', models.DateTimeField(verbose_name='출시 일시')),
            ],
            options={
                'verbose_name': '앱 버전',
                'verbose_name_plural': '앱 버전',
                'db_table': 'system_app_version',
                'ordering': ['-version_code'],
                'indexes': [models.Index(fields=['platform', 'is_active'], name='system_app__platfor_766ea9_idx'), models.Index(fields=['platform', 'version_code'], name='system_app__platfor_7de162_idx')],
                'unique_together': {('platform', 'version_code')},
            },
        ),
    ]
