# Generated by Django 5.2.7 on 2025-10-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='레코드가 생성된 시각', verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='레코드가 마지막으로 수정된 시각', verbose_name='수정일시')),
                ('recipe_sno', models.CharField(help_text='원본 RCP_SNO', max_length=50, unique=True, verbose_name='레시피 일련번호')),
                ('title', models.CharField(help_text='RCP_TTL', max_length=200, verbose_name='레시피 제목')),
                ('name', models.CharField(help_text='CKG_NM', max_length=100, verbose_name='요리명')),
                ('introduction', models.TextField(blank=True, help_text='CKG_IPDC', verbose_name='요리 소개')),
                ('servings', models.CharField(help_text='CKG_INBUN_NM (예: 4.0)', max_length=20, verbose_name='인분')),
                ('difficulty', models.CharField(help_text='CKG_DODF_NM (예: 아무나)', max_length=20, verbose_name='난이도')),
                ('cooking_time', models.CharField(help_text='CKG_TIME_NM (예: 30.0)', max_length=20, verbose_name='조리시간')),
                ('method', models.CharField(blank=True, help_text='CKG_MTH_ACTO_NM', max_length=50, verbose_name='조리방법')),
                ('situation', models.CharField(blank=True, help_text='CKG_STA_ACTO_NM', max_length=50, verbose_name='상황')),
                ('ingredient_type', models.CharField(blank=True, help_text='CKG_MTRL_ACTO_NM', max_length=50, verbose_name='재료별')),
                ('recipe_type', models.CharField(blank=True, help_text='CKG_KND_ACTO_NM', max_length=50, verbose_name='요리종류')),
                ('image_url', models.URLField(blank=True, help_text='RCP_IMG_URL', verbose_name='이미지 URL')),
                ('views', models.IntegerField(default=0, help_text='INQ_CNT', verbose_name='조회수')),
                ('recommendations', models.IntegerField(default=0, help_text='RCMM_CNT', verbose_name='추천수')),
                ('scraps', models.IntegerField(default=0, help_text='SRAP_CNT', verbose_name='스크랩수')),
            ],
            options={
                'verbose_name': '레시피',
                'verbose_name_plural': '레시피',
                'ordering': ['-created_at'],
            },
        ),
    ]
