# Generated by Django 5.2.7 on 2025-10-02 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='레코드가 생성된 시각', verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='레코드가 마지막으로 수정된 시각', verbose_name='수정일시')),
                ('original_name', models.CharField(help_text='CSV에서 파싱한 원본 재료명', max_length=100, verbose_name='원본 재료명')),
                ('normalized_name', models.CharField(help_text='매칭을 위해 정규화된 재료명 (기본값: original_name)', max_length=100, verbose_name='정규화 재료명')),
                ('category', models.CharField(choices=[('essential', '필수 재료'), ('seasoning', '조미료'), ('optional', '선택 재료')], default='essential', help_text='재료 카테고리 (필수/조미료/선택)', max_length=20, verbose_name='카테고리')),
                ('quantity', models.CharField(blank=True, help_text='재료의 수량 정보 (Phase 2 이후 활용)', max_length=50, verbose_name='수량')),
                ('is_essential', models.BooleanField(default=True, help_text='레시피에 필수적인 재료 여부', verbose_name='필수 재료')),
                ('recipe', models.ForeignKey(help_text='이 재료가 속한 레시피', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe', verbose_name='레시피')),
            ],
            options={
                'verbose_name': '재료',
                'verbose_name_plural': '재료',
                'ordering': ['recipe', 'category', 'original_name'],
            },
        ),
    ]
