# Generated by Django 5.2.7 on 2025-10-02 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='레코드가 생성된 시각', verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='레코드가 마지막으로 수정된 시각', verbose_name='수정일시')),
                ('name', models.CharField(help_text='통합된 재료명 (예: 돼지고기)', max_length=100, unique=True, verbose_name='정규화 재료명')),
                ('category', models.CharField(choices=[('meat', '육류'), ('vegetable', '채소류'), ('seafood', '해산물'), ('seasoning', '조미료'), ('grain', '곡물'), ('dairy', '유제품'), ('etc', '기타')], help_text='재료 분류', max_length=20, verbose_name='카테고리')),
                ('is_common_seasoning', models.BooleanField(default=False, help_text='대부분의 레시피에 사용되는 조미료 여부', verbose_name='범용 조미료')),
                ('description', models.TextField(blank=True, help_text='관리자용 메모', verbose_name='설명')),
            ],
            options={
                'verbose_name': '정규화 재료',
                'verbose_name_plural': '정규화 재료',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='normalized_ingredient',
            field=models.ForeignKey(blank=True, help_text='연결된 정규화 재료', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='recipes.normalizedingredient', verbose_name='정규화 재료'),
        ),
    ]
