# Generated by Django 5.2.7 on 2025-10-02 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_normalizedingredient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='레코드가 생성된 시각', verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='레코드가 마지막으로 수정된 시각', verbose_name='수정일시')),
                ('session_key', models.CharField(blank=True, help_text='비회원인 경우 세션 키', max_length=40, null=True, verbose_name='세션 키')),
                ('user', models.ForeignKey(blank=True, help_text='회원인 경우 사용자', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '냉장고',
                'verbose_name_plural': '냉장고',
                'db_table': 'recipes_fridge',
            },
        ),
        migrations.CreateModel(
            name='FridgeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='추가 일시')),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.fridge', verbose_name='냉장고')),
                ('normalized_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.normalizedingredient', verbose_name='정규화 재료')),
            ],
            options={
                'verbose_name': '냉장고 재료',
                'verbose_name_plural': '냉장고 재료',
                'db_table': 'recipes_fridge_ingredient',
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='fridge',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('session_key__isnull', False), _connector='OR'), name='fridge_owner_required'),
        ),
        migrations.AlterUniqueTogether(
            name='fridgeingredient',
            unique_together={('fridge', 'normalized_ingredient')},
        ),
    ]
