# Generated by Django 5.2.7 on 2025-10-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_fridge_fridgeingredient_fridge_fridge_owner_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_url',
            field=models.URLField(blank=True, help_text='만개의 레시피 상세 페이지 URL (https://www.10000recipe.com/recipe/{RCP_SNO})', verbose_name='레시피 URL'),
        ),
    ]
