# Generated by Django 5.2.7 on 2025-10-03 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_recipe_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fridge',
            index=models.Index(fields=['user'], name='fridge_user_idx'),
        ),
        migrations.AddIndex(
            model_name='fridge',
            index=models.Index(fields=['session_key'], name='fridge_session_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['original_name'], name='ingredient_original_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['normalized_name'], name='ingredient_normalized_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['recipe', 'category'], name='ingredient_recipe_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['normalized_ingredient', 'is_essential'], name='ingredient_norm_ess_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['category'], name='ingredient_category_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedingredient',
            index=models.Index(fields=['category'], name='normalized_category_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedingredient',
            index=models.Index(fields=['is_common_seasoning'], name='normalized_seasoning_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedingredient',
            index=models.Index(fields=['category', 'is_common_seasoning'], name='normalized_cat_season_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['name'], name='recipe_name_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['difficulty'], name='recipe_difficulty_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['method'], name='recipe_method_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['situation'], name='recipe_situation_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['recipe_type'], name='recipe_type_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['difficulty', 'cooking_time'], name='recipe_difficulty_time_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['-created_at'], name='recipe_created_idx'),
        ),
    ]
