# Generated by Django 5.2.7 on 2025-10-04 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_ingredientcategory_alter_ingredient_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalizedingredient',
            name='name',
            field=models.CharField(db_index=True, help_text='통합된 재료명 (예: 돼지고기)', max_length=100, unique=True, verbose_name='정규화 재료명'),
        ),
    ]
