# Generated by Django 5.2.7 on 2025-10-04 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_optimize_search_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_match_rate', models.FloatField(default=0.3, help_text='추천 레시피의 최소 매칭률 (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='최소 매칭률')),
                ('default_algorithm', models.CharField(choices=[('jaccard', 'Jaccard Similarity'), ('cosine', 'Cosine Similarity')], default='jaccard', help_text='추천에 사용할 기본 유사도 알고리즘', max_length=20, verbose_name='기본 알고리즘')),
                ('default_limit', models.IntegerField(default=20, help_text='기본으로 반환할 추천 레시피 개수 (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='기본 추천 개수')),
                ('exclude_seasonings_default', models.BooleanField(default=True, help_text='기본으로 범용 조미료를 제외할지 여부', verbose_name='기본 조미료 제외')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
            ],
            options={
                'verbose_name': '추천 설정',
                'verbose_name_plural': '추천 설정',
                'db_table': 'recipes_recommendation_settings',
            },
        ),
    ]
