# Generated by Django 5.2.7 on 2025-10-04 09:11

from django.db import migrations


def create_default_recommendation_settings(apps, schema_editor):
    """
    RecommendationSettings 기본 레코드 생성 (Singleton)

    관리자 페이지에서 바로 수정 가능하도록 초기 레코드를 생성합니다.
    """
    RecommendationSettings = apps.get_model('recipes', 'RecommendationSettings')

    # pk=1로 기본 설정 레코드 생성 (이미 존재하면 무시)
    RecommendationSettings.objects.get_or_create(
        pk=1,
        defaults={
            'min_match_rate': 0.3,
            'default_algorithm': 'jaccard',
            'default_limit': 20,
            'exclude_seasonings_default': True
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recommendationsettings'),
    ]

    operations = [
        migrations.RunPython(create_default_recommendation_settings),
    ]
