# Generated by Django 5.2.7 on 2025-10-04 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_create_default_recommendation_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationsettings',
            name='default_algorithm',
            field=models.CharField(choices=[('jaccard', 'Jaccard (자카드) - 교집합/합집합 방식, 직관적이고 간단함 (권장)'), ('cosine', 'Cosine (코사인) - 벡터 각도 방식, 재료 개수 차이에 덜 민감함')], default='jaccard', help_text='추천에 사용할 유사도 알고리즘. 사용자가 지정하지 않으면 이 값을 사용', max_length=20, verbose_name='기본 알고리즘'),
        ),
        migrations.AlterField(
            model_name='recommendationsettings',
            name='default_limit',
            field=models.IntegerField(default=20, help_text='API에서 기본으로 반환할 레시피 개수 (1-100). 사용자가 limit 파라미터를 지정하지 않으면 이 값을 사용합니다.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='기본 추천 개수'),
        ),
        migrations.AlterField(
            model_name='recommendationsettings',
            name='min_match_rate',
            field=models.FloatField(default=0.3, help_text='추천 레시피의 최소 매칭률 (0.0-1.0). 낮을수록 다양한 레시피 추천, 높을수록 엄격한 매칭', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='최소 매칭률'),
        ),
    ]
