apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration-{{ .Values.migration.version }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: db-migration
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
        - name: MODE
          value: "migration"
        - name: MIGRATION_MODE
          value: "db-migration"
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.database }}
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.database }}
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.database }}
              key: POSTGRES_PASSWORD
        - name: POSTGRES_SERVER
          value: {{ .Values.database.host }}
        - name: POSTGRES_PORT
          value: "{{ .Values.database.port }}"
        command: ["/entrypoint.sh"]
