apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

bases:
  - ../../base

commonLabels:
  environment: prod

images:
  - name: fridge2fork-admin-web
    newName: YOUR_DOCKERHUB_USERNAME/fridge2fork-admin-web-prod
    newTag: latest

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: fridge2fork-config
    behavior: merge
    literals:
      - node_env=production