"""Add system tables: platform_versions and system_status

Revision ID: 22124a8afa65
Revises: 003_feedback
Create Date: 2025-09-30 01:08:13.591961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22124a8afa65'
down_revision = '003_feedback'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('latest_version', sa.String(length=20), nullable=False),
    sa.Column('latest_build_number', sa.String(length=20), nullable=False),
    sa.Column('min_supported_version', sa.String(length=20), nullable=False),
    sa.Column('min_supported_build_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('download_url', sa.String(length=500), nullable=True),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('release_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_versions_id'), 'platform_versions', ['id'], unique=False)
    op.create_index(op.f('ix_platform_versions_platform'), 'platform_versions', ['platform'], unique=True)
    op.create_table('system_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=True),
    sa.Column('announcement_message', sa.Text(), nullable=True),
    sa.Column('update_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_status_id'), 'system_status', ['id'], unique=False)
    op.drop_index('ix_feedback_created', table_name='feedback')
    op.create_index(op.f('ix_feedback_created_at'), 'feedback', ['created_at'], unique=False)
    op.drop_constraint('ingredients_name_key', 'ingredients', type_='unique')
    op.drop_index('ix_ingredients_category_common', table_name='ingredients')
    op.drop_index('ix_ingredients_common', table_name='ingredients')
    op.drop_index('ix_ingredients_name', table_name='ingredients')
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=True)
    op.create_index(op.f('ix_ingredients_id'), 'ingredients', ['id'], unique=False)
    op.create_index(op.f('ix_ingredients_is_common'), 'ingredients', ['is_common'], unique=False)
    op.drop_index('ix_recipe_ingredients_compound', table_name='recipe_ingredients')
    op.drop_index('ix_recipe_ingredients_display_order', table_name='recipe_ingredients')
    op.drop_index('uk_recipe_ingredient', table_name='recipe_ingredients')
    op.create_index(op.f('ix_recipe_ingredients_id'), 'recipe_ingredients', ['id'], unique=False)
    op.drop_index('ix_recipes_category', table_name='recipes')
    op.drop_index('ix_recipes_difficulty', table_name='recipes')
    op.drop_index('ix_recipes_method', table_name='recipes')
    op.drop_index('ix_recipes_popularity', table_name='recipes')
    op.drop_index('ix_recipes_reg_date', table_name='recipes')
    op.drop_index('ix_recipes_time', table_name='recipes')
    op.drop_index('ix_recipes_title', table_name='recipes')
    op.create_index(op.f('ix_recipes_ckg_dodf_nm'), 'recipes', ['ckg_dodf_nm'], unique=False)
    op.create_index(op.f('ix_recipes_ckg_knd_acto_nm'), 'recipes', ['ckg_knd_acto_nm'], unique=False)
    op.create_index(op.f('ix_recipes_ckg_mth_acto_nm'), 'recipes', ['ckg_mth_acto_nm'], unique=False)
    op.create_index(op.f('ix_recipes_ckg_time_nm'), 'recipes', ['ckg_time_nm'], unique=False)
    op.create_index(op.f('ix_recipes_first_reg_dt'), 'recipes', ['first_reg_dt'], unique=False)
    op.create_index(op.f('ix_recipes_rcp_sno'), 'recipes', ['rcp_sno'], unique=False)
    op.create_index(op.f('ix_recipes_rcp_ttl'), 'recipes', ['rcp_ttl'], unique=False)
    op.drop_index('ix_fridge_added_at', table_name='user_fridge_ingredients')
    op.drop_index('ix_fridge_id', table_name='user_fridge_ingredients')
    op.drop_index('ix_fridge_ingredient', table_name='user_fridge_ingredients')
    op.drop_index('ix_fridge_session', table_name='user_fridge_ingredients')
    op.drop_index('ix_fridge_session_ingredient', table_name='user_fridge_ingredients')
    op.drop_constraint('uk_session_ingredient', 'user_fridge_ingredients', type_='unique')
    op.create_index(op.f('ix_user_fridge_ingredients_added_at'), 'user_fridge_ingredients', ['added_at'], unique=False)
    op.create_index(op.f('ix_user_fridge_ingredients_id'), 'user_fridge_ingredients', ['id'], unique=False)
    op.create_index(op.f('ix_user_fridge_ingredients_ingredient_id'), 'user_fridge_ingredients', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_user_fridge_ingredients_session_id'), 'user_fridge_ingredients', ['session_id'], unique=False)
    op.drop_index('ix_sessions_created', table_name='user_fridge_sessions')
    op.drop_index('ix_sessions_expires', table_name='user_fridge_sessions')
    op.drop_index('ix_sessions_session_id', table_name='user_fridge_sessions')
    op.create_index(op.f('ix_user_fridge_sessions_created_at'), 'user_fridge_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_fridge_sessions_expires_at'), 'user_fridge_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_fridge_sessions_session_id'), 'user_fridge_sessions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_fridge_sessions_session_id'), table_name='user_fridge_sessions')
    op.drop_index(op.f('ix_user_fridge_sessions_expires_at'), table_name='user_fridge_sessions')
    op.drop_index(op.f('ix_user_fridge_sessions_created_at'), table_name='user_fridge_sessions')
    op.create_index('ix_sessions_session_id', 'user_fridge_sessions', ['session_id'], unique=False)
    op.create_index('ix_sessions_expires', 'user_fridge_sessions', ['expires_at'], unique=False)
    op.create_index('ix_sessions_created', 'user_fridge_sessions', ['created_at'], unique=False)
    op.drop_index(op.f('ix_user_fridge_ingredients_session_id'), table_name='user_fridge_ingredients')
    op.drop_index(op.f('ix_user_fridge_ingredients_ingredient_id'), table_name='user_fridge_ingredients')
    op.drop_index(op.f('ix_user_fridge_ingredients_id'), table_name='user_fridge_ingredients')
    op.drop_index(op.f('ix_user_fridge_ingredients_added_at'), table_name='user_fridge_ingredients')
    op.create_unique_constraint('uk_session_ingredient', 'user_fridge_ingredients', ['session_id', 'ingredient_id'])
    op.create_index('ix_fridge_session_ingredient', 'user_fridge_ingredients', ['session_id', 'ingredient_id'], unique=False)
    op.create_index('ix_fridge_session', 'user_fridge_ingredients', ['session_id'], unique=False)
    op.create_index('ix_fridge_ingredient', 'user_fridge_ingredients', ['ingredient_id'], unique=False)
    op.create_index('ix_fridge_id', 'user_fridge_ingredients', ['id'], unique=False)
    op.create_index('ix_fridge_added_at', 'user_fridge_ingredients', ['added_at'], unique=False)
    op.drop_index(op.f('ix_recipes_rcp_ttl'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_rcp_sno'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_first_reg_dt'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_ckg_time_nm'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_ckg_mth_acto_nm'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_ckg_knd_acto_nm'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_ckg_dodf_nm'), table_name='recipes')
    op.create_index('ix_recipes_title', 'recipes', ['rcp_ttl'], unique=False)
    op.create_index('ix_recipes_time', 'recipes', ['ckg_time_nm'], unique=False)
    op.create_index('ix_recipes_reg_date', 'recipes', ['first_reg_dt'], unique=False)
    op.create_index('ix_recipes_popularity', 'recipes', ['inq_cnt', 'rcmm_cnt'], unique=False)
    op.create_index('ix_recipes_method', 'recipes', ['ckg_mth_acto_nm'], unique=False)
    op.create_index('ix_recipes_difficulty', 'recipes', ['ckg_dodf_nm'], unique=False)
    op.create_index('ix_recipes_category', 'recipes', ['ckg_knd_acto_nm'], unique=False)
    op.drop_index(op.f('ix_recipe_ingredients_id'), table_name='recipe_ingredients')
    op.create_index('uk_recipe_ingredient', 'recipe_ingredients', ['rcp_sno', 'ingredient_id'], unique=False)
    op.create_index('ix_recipe_ingredients_display_order', 'recipe_ingredients', ['rcp_sno', 'display_order'], unique=False)
    op.create_index('ix_recipe_ingredients_compound', 'recipe_ingredients', ['ingredient_id', 'rcp_sno', 'importance'], unique=False)
    op.drop_index(op.f('ix_ingredients_is_common'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_id'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.create_index('ix_ingredients_name', 'ingredients', ['name'], unique=False)
    op.create_index('ix_ingredients_common', 'ingredients', ['is_common'], unique=False)
    op.create_index('ix_ingredients_category_common', 'ingredients', ['category', 'is_common'], unique=False)
    op.create_unique_constraint('ingredients_name_key', 'ingredients', ['name'])
    op.drop_index(op.f('ix_feedback_created_at'), table_name='feedback')
    op.create_index('ix_feedback_created', 'feedback', ['created_at'], unique=False)
    op.drop_index(op.f('ix_system_status_id'), table_name='system_status')
    op.drop_table('system_status')
    op.drop_index(op.f('ix_platform_versions_platform'), table_name='platform_versions')
    op.drop_index(op.f('ix_platform_versions_id'), table_name='platform_versions')
    op.drop_table('platform_versions')
    # ### end Alembic commands ###