# Generated by Django 5.2.7 on 2025-10-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='사용자 이메일 주소 (로그인 ID)', max_length=254, unique=True, verbose_name='이메일')),
                ('username', models.CharField(blank=True, help_text='사용자명 (선택사항, 중복 허용)', max_length=150, null=True, verbose_name='사용자명')),
                ('is_active', models.BooleanField(default=True, help_text='사용자 활성 여부', verbose_name='활성 상태')),
                ('is_staff', models.BooleanField(default=False, help_text='관리자 사이트 접근 권한', verbose_name='스태프 권한')),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='사용자가 가입한 시각', verbose_name='가입일시')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'ordering': ['-date_joined'],
            },
        ),
    ]
