name: CI/CD for Admin Web

on:
  push:
    branches:
      - main
      - dev
      - develop
      - development
    paths:
      - 'admin/web/**'
      - '.github/workflows/ci-admin-web.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'admin/web/**'
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-push-admin-web:
    name: Build and Push Admin Web Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write
    outputs:
      sha: ${{ steps.vars.outputs.sha }}
      environment: ${{ steps.vars.outputs.environment }}
    env:
      BUILD_ENVIRONMENT: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate short SHA and environment
        id: vars
        run: |
          echo "sha=$(git rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT
          echo "environment=${{ env.BUILD_ENVIRONMENT }}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./admin/web
          file: ./admin/web/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            NODE_ENV=production
            NEXT_TELEMETRY_DISABLED=1
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/fridge2fork-admin-web-${{ steps.vars.outputs.environment }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/fridge2fork-admin-web-${{ steps.vars.outputs.environment }}:sha-${{ steps.vars.outputs.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy vulnerability scanner
        if: github.event_name != 'pull_request'
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/fridge2fork-admin-web-${{ steps.vars.outputs.environment }}:latest
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy results to GitHub Security
        if: github.event_name != 'pull_request'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

  update-infra-repository:
    name: Update Infrastructure Repository for Admin Web
    runs-on: ubuntu-latest
    needs: build-and-push-admin-web
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install ruamel.yaml GitPython

      - name: Update infra repository
        run: |
          python .github/workflows/scripts/update_infra_values.py sha-${{ needs.build-and-push-admin-web.outputs.sha }} ${{ secrets.INFRA_GITHUB_TOKEN }} admin-web