name: CI/CD for Admin Backend

on:
  push:
    branches:
      - main
      - dev
      - develop
      - development
    paths:
      - 'admin/backend/**'
      - '.github/workflows/ci-admin.yml'
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-push-admin:
    name: Build and Push Admin Backend Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      sha: ${{ steps.vars.outputs.sha }}
      environment: ${{ steps.vars.outputs.environment }}
    env:
      BUILD_ENVIRONMENT: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate short SHA and environment
        id: vars
        run: |
          echo "sha=$(git rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT
          echo "environment=${{ env.BUILD_ENVIRONMENT }}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./admin/backend
          file: ./admin/backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/fridge2fork-admin:${{ steps.vars.outputs.environment }}-latest
            ${{ secrets.DOCKERHUB_USERNAME }}/fridge2fork-admin:${{ steps.vars.outputs.environment }}-sha-${{ steps.vars.outputs.sha }}

