name: CI/CD for Scraper

on:
  push:
    branches:
      - main
      - dev
      - develop
      - development
    paths:
      - 'scrape/**'
      - '.github/workflows/ci-scrape.yml'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'scrape/**'
      - '.github/workflows/ci-scrape.yml'
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-push-scraper:
    name: Build and Push Scraper Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      sha: ${{ steps.vars.outputs.sha }}
      environment: ${{ steps.vars.outputs.environment }}
    env:
      BUILD_ENVIRONMENT: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate short SHA and environment
        id: vars
        run: |
          echo "sha=$(git rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT
          echo "environment=${{ env.BUILD_ENVIRONMENT }}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./scrape
          file: ./scrape/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/fridge2fork-${{ steps.vars.outputs.environment }}-scrape:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/fridge2fork-${{ steps.vars.outputs.environment }}-scrape:sha-${{ steps.vars.outputs.sha }}

  update-infra-repository:
    name: Update Infrastructure Repository for Scraper
    runs-on: ubuntu-latest
    needs: build-and-push-scraper
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install ruamel.yaml GitPython

      - name: Update infra repository
        run: |
          python .github/workflows/scripts/update_infra_values.py sha-${{ needs.build-and-push-scraper.outputs.sha }} ${{ secrets.INFRA_GITHUB_TOKEN }} scraper ${{ needs.build-and-push-scraper.outputs.environment }}
